/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface QuizAttempt {
  'topic' : Topic,
  'isCorrect' : boolean,
  'timestamp' : Time,
  'questionId' : string,
  'selectedAnswer' : string,
}
export type Time = bigint;
export type Topic = { 'newtons_first_law' : null } |
  { 'newtons_third_law' : null } |
  { 'tension_force' : null } |
  { 'free_body_diagram' : null } |
  { 'newtons_second_law' : null };
export interface TopicProgress {
  'topic' : Topic,
  'quizScore' : bigint,
  'lessonsCompleted' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllQuizAttempts' : ActorMethod<
    [],
    Array<[Principal, Array<QuizAttempt>]>
  >,
  'getAllTopicProgress' : ActorMethod<
    [],
    Array<[Principal, Array<TopicProgress>]>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserQuizHistory' : ActorMethod<[Principal], Array<QuizAttempt>>,
  'getUserTopicProgress' : ActorMethod<[Principal], Array<TopicProgress>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordQuizAttempt' : ActorMethod<[QuizAttempt], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateTopicProgress' : ActorMethod<[TopicProgress], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];