/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Topic = IDL.Variant({
  'newtons_first_law' : IDL.Null,
  'newtons_third_law' : IDL.Null,
  'tension_force' : IDL.Null,
  'free_body_diagram' : IDL.Null,
  'newtons_second_law' : IDL.Null,
});
export const Time = IDL.Int;
export const QuizAttempt = IDL.Record({
  'topic' : Topic,
  'isCorrect' : IDL.Bool,
  'timestamp' : Time,
  'questionId' : IDL.Text,
  'selectedAnswer' : IDL.Text,
});
export const TopicProgress = IDL.Record({
  'topic' : Topic,
  'quizScore' : IDL.Nat,
  'lessonsCompleted' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllQuizAttempts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(QuizAttempt)))],
      ['query'],
    ),
  'getAllTopicProgress' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(TopicProgress)))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserQuizHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(QuizAttempt)],
      ['query'],
    ),
  'getUserTopicProgress' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(TopicProgress)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordQuizAttempt' : IDL.Func([QuizAttempt], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateTopicProgress' : IDL.Func([TopicProgress], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Topic = IDL.Variant({
    'newtons_first_law' : IDL.Null,
    'newtons_third_law' : IDL.Null,
    'tension_force' : IDL.Null,
    'free_body_diagram' : IDL.Null,
    'newtons_second_law' : IDL.Null,
  });
  const Time = IDL.Int;
  const QuizAttempt = IDL.Record({
    'topic' : Topic,
    'isCorrect' : IDL.Bool,
    'timestamp' : Time,
    'questionId' : IDL.Text,
    'selectedAnswer' : IDL.Text,
  });
  const TopicProgress = IDL.Record({
    'topic' : Topic,
    'quizScore' : IDL.Nat,
    'lessonsCompleted' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllQuizAttempts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(QuizAttempt)))],
        ['query'],
      ),
    'getAllTopicProgress' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(TopicProgress)))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserQuizHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(QuizAttempt)],
        ['query'],
      ),
    'getUserTopicProgress' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(TopicProgress)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordQuizAttempt' : IDL.Func([QuizAttempt], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateTopicProgress' : IDL.Func([TopicProgress], [], []),
  });
};

export const init = ({ IDL }) => { return []; };